#!/bin/bash

set -e

# Backend checks.
cd backend

. venv/bin/activate

black --check likes
flake8 likes
mypy likes
python manage.py test

deactivate

# Frontend checks.
cd ../frontend

npm run prettier:check
npm run eslint
